<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>cl2j.DataStore</PackageId>
    <Description>Multi-provider CRUD repository abstraction. Extensible via Dependency Injection.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\cl2j.FileStorage\cl2j.FileStorage\cl2j.FileStorage.csproj" />
  </ItemGroup>
</Project>
