<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>cl2j.Smapper</PackageId>
    <Description>Lightweight reflection-based object-to-object mapper.</Description>
    <AssemblyName>cl2j.Smapper</AssemblyName>
    <RootNamespace>cl2j.Smapper</RootNamespace>
  </PropertyGroup>
</Project>
