<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>cl2j.DataStore.Json</PackageId>
    <Description>JSON file provider for cl2j.DataStore.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\cl2j.DataStore\cl2j.DataStore.csproj" />
  </ItemGroup>
</Project>
