<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>cl2j.FileStorage.Provider.AzureBlobStorage</PackageId>
    <Description>Azure Blob Storage provider for cl2j.FileStorage.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\readme.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.26.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cl2j.FileStorage\cl2j.FileStorage.csproj" />
  </ItemGroup>
</Project>
