<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<IsPackable>true</IsPackable>
		<PackageId>cl2j.DataStore.Database-deprecated</PackageId>
		<Description>Deprecated SQL database repository implementation for cl2j.DataStore. Kept for backward compatibility during migration to cl2j.Database.</Description>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="System.Data.SqlClient" Version="4.9.1" />
		<PackageReference Include="Dapper" Version="2.1.72" />
		<PackageReference Include="Dapper.Contrib" Version="2.0.78" />
		<PackageReference Include="cl2j.DataStore" Version="2.0.0" />
	</ItemGroup>

	<ItemGroup>
		<None Include=".editorconfig" />
	</ItemGroup>

</Project>
