<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>cl2j.WebTooling</PackageId>
    <Description>ASP.NET Core utilities: Claims, HttpClient, and HttpRequest extensions.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\cl2j.Tooling\cl2j.Tooling.csproj" />
  </ItemGroup>
</Project>
