using cl2j.Database.DataAnnotations;

namespace DatabaseSample.Models
{
    [Table("Cat")]
    public record Category
    {
        [Column(Key = KeyType.AutoGeneratedKey, Length = 36)]
        public string CategoryId { get; set; } = null!;

        [Column(Length = 50)]
        public string Name { get; set; } = null!;

        public override string ToString()
        {
            return $"{CategoryId} [Name={Name}]";
        }
    }
}
