namespace cl2j.Database.DataAnnotations
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)]
    public class ColumnAttribute : Attribute
    {
        /// <summary>
        ///     The name of the column the property is mapped to.
        /// </summary>
        public string Name { get; set; } = string.Empty;

        /// <summary>
        ///     The database provider specific data type of the column the property is mapped to.
        /// </summary>
        public string TypeName { get; set; } = string.Empty;

        /// <summary>
        ///     Maximum allowable length of the data.
        /// </summary>
        public int Length { get; set; }

        /// <summary>
        ///     Number of decimals.
        /// </summary>
        public int Decimals { get; set; }

        /// <summary>
        ///     Indicate if the attribute is a key and the type of the key
        ///     
        ///     None: No a key
        ///     Key: A primary key
        ///     AutoGeneratedKey: The value of the key will be generated by the library. Only available on string type 
        /// </summary>
        public KeyType Key { get; set; } = KeyType.None;

        /// <summary>
        ///     Indicate that a property, field is required.
        /// </summary>
        public bool Required { get; set; }

        /// <summary>
        ///     Indicate that the property is serialized as a JSON.
        /// </summary>
        public bool Json { get; set; }

        /// <summary>
        ///     The property default value
        /// </summary>
        public string? Default { get; set; } = "";
    }
}
